### ISSUE TITLE
"HowTo" ：the 'mvn ' command has some errors

### ISSUE THREAD

**Issue by gengxiaoxiaoxin** [or-tools/java_or-tools#2]
```sh
mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile=ortools-java-8.2.8710.jar
```
an error message is thrown.

> The goal you specified requires a project to execute but there is no POM in this directory

it should be:

```sh
mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile="ortools-java-8.2.8710.jar"
```

and also this:
```sh
mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile=ortools-linux-x86-64-8.2.8710.jar
change to
mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile="ortools-win32-x86-64-8.2.8710.jar"
```

**Comment by Mizux** [comment]
well it is not needed on unix...
https://github.com/or-tools/java_or-tools/blob/474df813dd76b130a223edd4740660b11d62dbd9/.github/workflows/linux.yml#L26-L27
and
https://github.com/or-tools/java_or-tools/blob/474df813dd76b130a223edd4740660b11d62dbd9/.github/workflows/macos.yml#L26-L27

agree for windows
https://github.com/or-tools/java_or-tools/blob/474df813dd76b130a223edd4740660b11d62dbd9/.github/workflows/win.yml#L29-L30
